Merge Makefile changes to support Niel's work (for certficate validation) along with Jeff's work (for InstallBuilder support).
Note that 'make kit' won't work until InstallBuilder data files are checked in (within the short future).

diff --git a/build/configure b/build/configure
--- a/build/configure
+++ b/build/configure
@@ -8,6 +8,7 @@ enable_purify_agent=""
 enable_purify_server=""
 enable_omi_tools=""
 enable_omi_tools_flag=0
+build_type=Release
 
 # Default OMI qualifiers for build purposes
 omi_configure_quals=""
@@ -30,7 +31,16 @@ do
 
     --enable-debug)
       enable_debug="--enable-debug"
+      build_type=Debug
       enable_debug_flag=1
+    ;;
+
+    --enable-ulinux)
+      if [ `uname` != "Linux" ]; then
+          echo "Cannot build for ULINUX on non-Linux platforms"
+          exit 1
+      fi
+      ULINUX=1
     ;;
 
     --enable-purify-agent)
@@ -72,6 +82,7 @@ This script configures SCXOM for building. Type the following commands.
 OPTIONS:
     -h, --help                  Print this help message.
     --enable-debug              Perform a debug build.
+    --enable-ulinux             Specifies platform as ULINUX (Linux only).
     --enable-purify-agent       Allow agent to be run with purify (memory leak detection)
     --enable-purify-server      Allow server to be run with purify (memory leak detection)
     --enable-omi-tools          Build to allow use of OMI tools (omischema and omireg)
@@ -82,10 +93,110 @@ fi
 
 omi_configure_quals="${enable_debug} ${enable_purify_agent} ${enable_purify_server} ${enable_omi_tools} ${omi_configure_quals}"
 
+
+
+
+# Note: Most of this code came from the PAL configure file
+
+set_ulinux_pf() 
+{
+    PF_MAJOR=1
+    PF_MINOR=0
+    PF_DISTRO=ULINUX
+    PF_DISTRO_ULINUX_D=`[ -e /usr/bin/dpkg ] && echo 1`
+    if [ -n "$PF_DISTRO_ULINUX_D" ]; then
+        PF_DISTOR_ULINUX_R=
+	BUILD_DPKG=1
+	PKG_SUFFIX=deb
+    else
+        PF_DISTRO_ULINUX_R=`[ -e /usr/bin/rpmbuild ] && echo 1`
+	BUILD_RPM=1
+    fi
+}
+
+uname=`uname`
+case $uname in
+    Linux)
+        PF=Linux
+	PKG_SUFFIX=rpm
+        if [ -e /etc/SuSE-release ]; then 
+            CHECK_SUSE=1
+        fi
+        if [ -e /etc/redhat-release ]; then
+            CHECK_RHEL_OR_CENTOS=1
+        fi
+        if [ -n "$CHECK_RHEL_OR_CENTOS" ]; then
+            CHECK_CENTOS=`grep -i "Red Hat" /etc/redhat-release || echo 1`
+            if [ "$CHECK_CENTOS" != "1" ]; then
+                CHECK_RHEL=1
+            fi
+        fi
+
+        if [ "$ULINUX" = "1" ]; then
+	    set_ulinux_pf
+	    BUILD_RPM=1
+	    BUILD_DPKG=1
+        elif [ -n "$CHECK_SUSE" ]; then
+            PF_MAJOR=`head -n 1 /etc/SuSE-release | sed 's/.* \([0-9][0-9]*\)[ \.].*/\1/'`
+            PF_MINOR=`(head -n 1 /etc/SuSE-release | sed 's/.* [0-9][0-9]*[\.]\([0-9][0-9]*\).*/\1/') | grep -v '[^0-9]' || echo '0'`
+            PF_DISTRO=SUSE
+        elif [ -n "$CHECK_RHEL" ]; then
+            PF_MAJOR=`head -n 1 /etc/redhat-release | sed 's/.* \([0-9][0-9]*\)[ \.].*/\1/'`
+            PF_MINOR=`(head -n 1 /etc/redhat-release | sed 's/.* [0-9][0-9]*[\.]\([0-9][0-9]*\).*/\1/') | grep -v '[^0-9]' || echo '0'`
+            PF_DISTRO=REDHAT
+        else
+	    set_ulinux_pf
+        fi
+
+        case `uname -m` in
+            *64*)
+                PF_ARCH=x64
+                ARCH=x64
+            ;;
+            *86*)
+                PF_ARCH=x86
+                ARCH=ia32
+            ;;
+            *athlon*)
+                PF_ARCH=x86
+                ARCH=ia32
+            ;;
+            *)
+                PF_ARCH=UNKNOWN
+                ARCH=UNKNOWN
+            ;;
+        esac
+
+        if [ "$PF_ARCH" = "x86" ]; then
+            PF_WIDTH=32
+        else
+            PF_WIDTH=64
+        fi
+    ;;
+
+esac
+
+if [ "$uname" = "Linux" ]; then
+    BUILD_CONFIGURATION=${PF}_${PF_DISTRO}_${PF_MAJOR}.${PF_MINOR}_${PF_ARCH}_${PF_WIDTH}_${build_type}
+else
+    BUILD_CONFIGURATION=${PF}_${PF_MAJOR}.${PF_MINOR}_${PF_ARCH}_${PF_WIDTH}_${build_type}
+fi
+
 cat <<EOF > config.mak
 ENABLE_DEBUG=$enable_debug_flag
 PERFORM_OMI_MAKEINSTALL=$enable_omi_tools_flag
 OMI_CONFIGURE_QUALS=$omi_configure_quals
+
+BUILD_TYPE=$build_type
+PF=$PF
+PF_MAJOR=$PF_MAJOR
+PF_MINOR=$PF_MINOR
+PF_ARCH=$PF_ARCH
+ARCH=$ARCH
+PF_WIDTH=$PF_WIDTH
+PF_DISTRO=$PF_DISTRO
+ULINUX=$ULINUX
+BUILD_CONFIGURATION=$BUILD_CONFIGURATION
 EOF
 
 # Fix permissions in case they aren't executable - and then configure OMI
